server:
  port: 20001

eureka:
  instance:
    #hostname: 10.11.1.111
    ip-address: 10.11.1.111
    # 使用IP地址配置高可用
    prefer-ip-address: true
    # 增加配置，统一实例命名
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
    #registry:
      # 指定每分钟期望收到的续约次数值
      #expected-number-of-clients-sending-renews: 2
  client:
    # 单节点注册中心，不需要向注册中心注册自己，为false
    # 高可用注册中心，注册中心之间需要相互注册，为true （默认为true）
    #register-with-eureka: false
    # 单节点，仅维护服务实例，不需要检索服务，为false
    # 高可用，需要获取服务，为true （默认为true）
    #fetch-registry: true
    service-url:
      defaultZone: http://10.11.1.130:20002/eureka/
  server:
    # eureka自我保护，默认为true ； 不建议关闭自我保护，建议调整renewal-percent-threshol阈值；
    #enable-self-preservation: true
    # 剔除过期服务任务间隔
    #eviction-interval-timer-in-ms: 30000
    # 每分钟需要收到续约率的阈值，
    renewal-percent-threshold: 0.5
    # 指定updateRenewalThreshold定时任务调度频率
    #renewal-threshold-update-interval-ms:  60000

spring:
  application:
    name: eureka-server
  #cloud:
    #inetutils:
      #default-ip-address: 10.11.1.111
