server:
  port: 20002

eureka:
  instance:
    #hostname: 10.11.1.130
    ip-address: 10.11.1.130
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
    #registry:
      #expected-number-of-clients-sending-renews: 2
  client:
    #register-with-eureka: true
    #fetch-registry: true
    service-url:
      defaultZone: http://10.11.1.111:20001/eureka/
  server:
    #enable-self-preservation: true
    #eviction-interval-timer-in-ms: 30000
    renewal-percent-threshold: 0.5
    #renewal-threshold-update-interval-ms:  60000

spring:
  application:
    name: eureka-server
  #cloud:
    #inetutils:
      #default-ip-address: 10.11.1.130


